# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab1/Basys3_Master.xdc

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0}]

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1}]

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]
