# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.cache/wt [current_project]
set_property parent.project_path P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_3/Lab_3.sim/sim_1/behav/rrcos8-fir-ip.coe
add_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_3/Lab_3.sim/sim_1/behav/rrcos8-brom.coe
add_files -quiet P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp
set_property used_in_implementation false [get_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.runs/dds_compiler_0_synth_1/dds_compiler_0.dcp]
add_files -quiet P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_ip P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc]
set_property used_in_implementation false [get_files -all p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.dcp]
set_property is_locked true [get_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci]

read_ip P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
set_property used_in_implementation false [get_files -all p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc]
set_property used_in_implementation false [get_files -all p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.dcp]
set_property is_locked true [get_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci]

read_ip P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
set_property is_locked true [get_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_4/Lab_4.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_vhdl -library xil_defaultlib {
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/SerialTx.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/SerialRx.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/RRC_Pulse_Shaper.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/RRC_Matched_Filter.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/Modulator.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/IQ_to_Char.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/Demodulator.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/CRloop.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/Char_to_IQ.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/BufferFSM.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/mux7seg.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/ModemTx.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/ModemRx.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/ClockDivider.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/imports/lab1top.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/new/test_top.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/new/pmodAD1.vhd
  P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/sources_1/imports/new/pmodDA2.vhd
}
read_xdc P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/constrs_1/imports/Lab1/Basys3_Master.xdc
set_property used_in_implementation false [get_files P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_5/Lab_5.srcs/constrs_1/imports/Lab1/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file lab5top.hwdef }
synth_design -top lab5top -part xc7a35tcpg236-1
write_checkpoint -noxdef lab5top.dcp
catch { report_utilization -file lab5top_utilization_synth.rpt -pb lab5top_utilization_synth.pb }
