# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_3/Lab_3.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_3/Lab_3.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_3/Lab_3.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
# IP: The module: 'fir_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/15spring/engs128/workspace/Brett_and_Matt/lab_workspace/Lab_3/Lab_3.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
